### PR TITLE
[test] rosbridge v2 protocol testing: advertise/unadvertise op

### PR DESCRIPTION
**Pull request by qiuzhong**
advertise/unadvertise operation test cases added.

### CODE REVIEW

**Comment by qiuzhong** [comment]
Please don't merge as some test cases will not pass as spec not completely implemented.

**Comment by qiuzhong** [comment]
I'm blocked by the fact that the CI on Windows failed while succeeded on Linux. I'm fixing it.

**Comment by minggangw** [comment]
I suppose you have more than one WebSockets server instances, which will be listening the same port. This may lead to the TCP error, please try use different port or guarantee there is only one server instance at any time.

**Comment by qiuzhong** [comment]
Using different ports for multiple server instances doesn't help. I'm trying to avoid creating/destroying multiple bridge servers in my test cases to see if it can help.

**Comment by minggangw** [comment]
It seems the windows ci doesn't complain :)

**Comment by qiuzhong** [comment]
Finally  it passed on Windows CI!

**Comment by minggangw** [comment]
So can I merge this PR now, if you will not change it any more?

**Comment by qiuzhong** [comment]
I think you can merge it now.

**Comment by minggangw** [comment]
OK, merging...

**Pull request merged**
