### PR TITLE
[test]Add rosbridge protocol test cases: publish

### PR DESCRIPTION
**Pull request by qiuzhong**
Add test cases for testing rosbridge v2 protocol on `publish` operation. (+8)

### CODE REVIEW

**Comment by qiuzhong** [comment]
The test cases will not pass due to #49. So please don't merge until #49 has been resolved.

**Comment by minggangw** [comment]
Hi @qiuzhong I have added the compatibility section into README, please update the test cases to treat the result as **error** if the subset of the message is not specified when publishing a topic.

**Comment by qiuzhong** [comment]
OK. I got it. Thanks. I'll update this PR soon!

**Comment by qiuzhong** [comment]
@minggangw , CI passed now.

**Comment by minggangw** [comment]
Thanks, will merge soon.

**Pull request merged**
